lighty:
    restconf:
        keyStorePassword: ENC[AES256_GCM,data:6LVklBM8hlI=,iv:wQUwPyESGeeDF8PWl2eo2ksmcdHARk5ofRWuh9z3SKM=,tag:Z/wdB+DqgKPgZARoFTanMw==,type:str]
        trustKeyStorePassword: ENC[AES256_GCM,data:IZFbKGOEH+I=,iv:JQjv6M4saMjr8pZQ2jWze+Nlst5A0YhAmJDTV+sVe5Q=,tag:Jmhd0m4yMGWrrwWWaA4q6w==,type:str]
    netconfNorthbound:
        username: ENC[AES256_GCM,data:QCI2jkA=,iv:Py6l3NSvoKtAJkJXwxbrNqSMkQ45F58K3Wz6axJV7Ks=,tag:ZGFZJlRK70f2iykjnYrZCg==,type:str]
        password: ENC[AES256_GCM,data:396oxDY=,iv:W1rwYJFvu9Zde48cQXcR2QbwNZpaeiHyFIrHih8Ubao=,tag:0b82iVEbmlq2++eCGe3IoQ==,type:str]
    aaa:
        username: ENC[AES256_GCM,data:MHxO,iv:DIuHEmNFVWY9LPYcPjvUiF91wdrzBpw3aRquK6M+DVI=,tag:JQbQyUVCokjfjAmiDTUgwQ==,type:str]
        password: ENC[AES256_GCM,data:V/5y,iv:dbGlnt0AhZfrULGPDaED4+eW6MEer7tOzeA7f5BhZhc=,tag:wpwS87QyNYI/2JcQG4GnRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ld8kazczrrhz6n203ndz4st6794wd6atdl0he0jq56vwt5sjuqs38x8qe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZY2xSMU1qZ252aldIOENP
            VWZFYVlFdm5rWnVvcTZ2WFhwalZlTG8wQVZFCk9EL1dLSkFOTFJRUVdSM0pOaUF2
            dHhLRUVZc1pTWm9RQnZYZlRBL05PckkKLS0tIFVHQ1lsZlhhM3VyTXFCOFBwbHhM
            VE1JT3ozbjBBQlhWeVlVWUU5cTdaQ28KfViHpOLMlgdQfvRPU7jmaIJp+LzCuZbR
            kgBFfh+uq9KRve5sOMD+Rs+B6fXf1qJhw73LP+XXX9IOIVjB6+JoDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-23T17:08:54Z"
    mac: ENC[AES256_GCM,data:lAqCKH6z8v2j8IWETDrbiRGryI35itzkroLjce1NgXBJkOYAZNc3ne8F6ItQ1nmRp1c2ZvCEdIhGabrGFv+KE6Hl8ctSAbyJ6dWyalaay2an2ekuXuawhMDcEPA+E6zWTGq+KJvio/Sse7gSxJczvEYcDQk/WpIMdXX3u9Clm+8=,iv:j+EVo18ZZ9wrl4JZr51K76+FhjajfZcKt0tdO7/WLwc=,tag:pV1PUEVvelPsa/V+ACH9XQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
